# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Library', '0007_auto_20171023_1248'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinbasket',
            name='product',
        ),
        migrations.AddField(
            model_name='orderinbasket',
            name='book_id',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='orderinbasket',
            name='books',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Library.Book'),
        ),
        migrations.AlterField(
            model_name='order',
            name='appendage',
            field=models.TextField(blank=True, max_length=2048),
        ),
    ]
