# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20171029_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinbasket',
            name='books',
        ),
    ]
