# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Library', '0007_auto_20171023_1248'),
        ('orders', '0003_remove_orderinbasket_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinbasket',
            name='books',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Library.Book'),
        ),
    ]
