# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderinbasket_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinbasket',
            name='books',
        ),
    ]
