# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20171106_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='session_key_product_in_order',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
