# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_productinorder_session_key_product_in_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='session_key_in_order',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
