# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20171118_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
